import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const urbanist = localFont({
  src: [
    {
      path: "../public/font/Urbanist-Regular.ttf",
      weight: "400",
    },
    {
      path: "../public/font/Urbanist-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-urbanist",
  className: "font-urbanist",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${urbanist.className} ${urbanist.className}`}>
        {children}
      </body>
    </html>
  );
}
