"use client"
import './globals.css'
import localFont from 'next/font/local'
import {Urbanist} from "next/font/google"
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import {
    ThirdwebProvider,
    coinbaseWallet,
    metamaskWallet,
    walletConnect,
    paperWallet,
    magicLink,
    smartWallet
} from "@thirdweb-dev/react"

const primary = localFont({src: '../../public/fonts/aquire.woff2', display: 'swap', variable: '--font-primary'})

const primaryBold = localFont({
    src: '../../public/fonts/aquire-bold.woff2',
    display: 'swap',
    variable: '--font-primary-bold'
})

const secondary = Urbanist({display: 'swap', variable: '--font-secondary', subsets: ['latin-ext']})
const activeChain = "ethereum"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" className={` ${primary.className} ${primaryBold.className}`}>
        <body>
        <ThirdwebProvider activeChain={activeChain}
                          supportedWallets={[
                              metamaskWallet(),
                              coinbaseWallet(),
                              walletConnect(),

                          ]}

        >

            <Navbar/>
            {children}
            <Footer/>
        </ThirdwebProvider>
        </body>
        </html>
    )
}
