import './globals.css'
import localFont from 'next/font/local'

const primary = localFont({src: '../../public/fonts/aquire.woff2', display: 'swap',variable: '--font-primary'})

const primaryBold = localFont({src: '../../public/fonts/aquire-bold.woff2', display: 'swap',variable: '--font-primary-bold'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${primary.className} ${primaryBold.className}`}>
      <body >{children}</body>
    </html>
  )
}
