import './globals.css'
import localFont from 'next/font/local'
import {Urbanist} from "next/font/google"
import Navbar from './components/Navbar'
import Footer from './components/Footer'

const primary = localFont({src: '../../public/fonts/aquire.woff2', display: 'swap', variable: '--font-primary'})

const primaryBold = localFont({
    src: '../../public/fonts/aquire-bold.woff2',
    display: 'swap',
    variable: '--font-primary-bold'
})

const secondary = Urbanist({display: 'swap', variable: '--font-secondary', subsets: ['latin-ext']})


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en" className={` ${primary.className} ${primaryBold.className}`}>
        <body>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    )
}
